'use strict';

angular.module('ices').config(function($translateProvider) {
    $translateProvider.translations('en', {
        'MENU_HOME': 'HOME',
        'MENU_ABOUT': 'ABOUT US',
        'MENU_MOTIVATION': 'Motivation',
        'MENU_GOAL': 'Objectives',
        'MENU_ORG': 'Structure',
        'MENU_DIRECTIVE': 'Directive',
        'MENU_EXDIRECTIVE':'Ex Directive',
        'MENU_STUDY': 'STUDY IN SWITZERLAND',
        'MENU_ICES': 'ICES COMMUNITY',
        'MENU_REQUIRIMENTS': 'Requirements',
        'MENU_BENEFITS': 'Benefits of being member',
        'MENU_MEMBERSHIP':'Annual membership',
        'MENU_SIGN_IN': 'Sign in form',
        'MENU_EVENT': 'EVENTS',
        'MENU_NEWS': 'NEWS',
        'MENU_PHOTO': 'PHOTOS',
        'MENU_CONTACT': 'CONTACT',
        'FOOTER_CONTACT_US': 'Contact us',
        'FOOTER_PARTNER':'Collaborators / Partners',
        'TITLE_ABOUT': 'About us?',
        'TITLE_MOTIVATION': 'What Motivates ICES?',
        'TITLE_GOAL': 'Objectives',
        'TITLE_PPAL_GOAL': 'These are our main objectives',
        'TITLE_ORG': 'Structure',
        'TITLE_OUR_ORG': 'Our structure',
        'TITLE_DIRECTIVE':'Directive',
        'MAIN_TITLE_INDEX': 'ICES',
        'CONTACT_TEXT' : 'Please fill out the form and we’ll get back to you soon.',
        'NAME_CONTACT': 'Name',
        'MAIL_CONTACT' : 'Mail',
        'SUBJECT_CONTACT': 'Subject',
        'MESSAGE_CONTACT': 'Message',
        'SUBMIT_CONTACT' : 'Send',
        'CAROUSEL_TEXT': 'ICES is constituted by researchers, students and professionals who work in Switzerland',
        'CAROUSEL_TEXT2': 'ICES is interested in the Chilean-Swiss collaborative research',
        'ABOUT_US': 'ICES (stands for the Spanish version of Chilean Researchers in Switzerland) is a non-profit association formed by a group of researchers, academics, students and professionals who develop their respective activities in Switzerland, interested in the collaboration between Chile and Switzerland in every field of knowledge and research.',
        'MOTIVATION': 'ICES seeks to contribute to the academic and professional collaboration between Chile and Switzerland. Based on our academic and professional experiences in Switzerland, we believe that there are many opportunities for scientific and professional collaboration between institutions of these two countries. We think that the academic, professional and even personal life of the Chilean researchers in Switzerland can profit from the advices and past experiences of people who are already working in this country. Our main motivation is to create the opportunities for Chilean researchers in Switzerland to contact each other, interchange experiences and explore new academic challenges together with Chilean and Swiss organizations. Also, we want to be an information platform in order to facilitate the exchange of Chilean students in Switzerland.',
        'GOAL': 'The objectives of our association can be divided in three main levels, going from the short-term in the first level to the long-term in the third:',
        'GOAL_LEVEL1': 'Level 1: Support Chilean researchers through their entire stay in Switzerland',
        'GOAL_LIST1_LEVEL1': 'Create an information platform for researchers and students in Chile interested in Switzerland for their academic and professional career opportunities.',
        'GOAL_LIST2_LEVEL1': 'Facilitate the integration of new Chilean researchers and students in Switzerland.',
        'GOAL_LIST3_LEVEL1': 'Strengthen the academic and scientific links between Chilean researchers, academics, students and professionals living in Switzerland.',
        'GOAL_LEVEL2': 'Level 2: Promotion of scientific and professional collaboration between Chilean and Swiss institutions and individuals',
        'GOAL_LIST1_LEVEL2': 'Create a platform where Chilean and Swiss researchers and students can share information, solve questions and find project partners or career opportunities in both countries.',
        'GOAL_LIST2_LEVEL2': 'Foster the development of new scientific and academic projects and initiatives involving both countries.',
        'GOAL_LIST3_LEVEL2':'Show Chile in Switzerland as a valuable opportunity for research and collaboration.',
        'GOAL_LEVEL3': 'Level 3: Participate in the discussion for the scientific and academic development of Chile',
        'GOAL_LIST1_LEVEL3': 'Participate and collaborate with different associations and networks of Chilean researchers in Chile and abroad.',
        'GOAL_LIST2_LEVEL3': 'Contribute from our experience to the development of policies for the reintegration of researchers and students returning to Chile. In particular, we would like to help students that are part of the Becas Chile program for post-graduate studies.',
        'STRUCTURE':'The organs of the association are:',
        'STRUCTURE_LIST1': 'The general assembly',
        'STRUCTURE_LIST2': 'The financial and administrative organ',
        'STRUCTURE_LIST3': 'The communication organ',
        'STRUCTURE_LIST4': 'The Directive board',
        'SHOW_BIO': 'Show biography',
        'HIDE_BIO': 'Hide biography',
        'PRESIDENCY'     : 'Presidency',
        'NAME_PRESIDENT' : 'Lorenzo Reyes',
        'BIO_PRESIDENT'  : 'Lorenzo Reyes-Chamorro was born in Santiago, Chile, on September 8, 1984. He received the B.Sc. degree in Electrical Engineering in 2007 and the professional diploma on Electrical Engineer in 2009 from the University of Chile.From 2009 to 2012 he worked as a Researcher in the Energy Center of the Physical and Mathematical Sciences Faculty in University of Chile,first as a project engineer but then leading the project ESUSCON which had as goal the transformation of Huatacondo (North of Chile) to become the first energetically self-sustainable village in Latin America. During that time he was also Invited Professor in several subjects in the Department of Electrical Engineering, being part of the review committee of various candidates to the Electrical Engineer diploma.Since January 2013, he has been working toward the Ph.D. degree at the Distributed Electrical System Laboratory (DESL), Swiss Federal Institute of Technology of Lausanne (EPFL), Switzerland.Lorenzo is married with 1 child. They currently live in Lausanne.',
        'SECRETARY' : 'Secretary',
        'NAME_SECRETARY': 'Felipe Orellana',
        'BIO_SECRETARY' : 'Felipe (October, 1985) was born in San Fernando, in the heart of the Colchagua Valley, O’Higgins Region, Chile. He is a Mining Engineer and holds a Master degree in Underground Mining from Universidad de Chile (2012).He was granted with the Anglo American Scholarship (2008-2010) of the Department of Mining Engineering. He was Vice-president (2008) and President (2009) of the Mining Student Association. He also worked at the Advanced Mining Technology Centre (AMTC) in the research group for mining design. His Masters thesis tackled the impact of a new ore extraction technology for massive underground mining. Before coming to Switzerland, he worked at HATCH Engineering and IM2 Codelco, and was involved in CODELCO and Rio Tinto projects.Felipe holds an adjunct professor position at the Mining Engineering Department at the Universidad de Chile. He is currently working on his doctoral studies at the Laboratory of Rocks Mechanics – EPFL, Lausanne, Switzerland. His main interests are rock mechanics, mining, tunnelling and engineering geology.',
        'NAME_SECRETARY2': 'Joaquín Bastías',
        'BIO_SECRETARY2' : 'From Puente Alto, Santiago, Joaquín Bastías studied geology in the University of Chile, after some brief experience in the industry conducted studies for a Master in Science in Geology at the same university. The research area is focused in the tectonic and thermal evolution of the Antarctic Peninsula, place where he has performed several field seasons, as also collaborative research with different institutions in Chile and abroad.Since the 2015 he is in Switzerland as a PhD candidate in Earth Sciences in the University of Geneva. His doctoral thesis, likewise his former research, is focused in subjects such as geochronology, geochemistry and thermochronology.',
        'TREASURER'     : 'Treasurer',
        'NAME_TREASURER': 'Oscar Sepúlveda',
        'BIO_TREASURER' :'Oscar Sepúlveda Steiner was born in Santiago, Chile, on May 28, 1989. He is a professional Civil Engineer from Universidad de Chile and holds a M.Sc. in Water Resources & Environment also from Universidad de Chile. He was granted with the National Master scholarship from CONICYT (2013-2014).He is interested in environmental fluid dynamics and transport processes in aquatic systems. His main focus is performing research in physical limnology based on field measurements and numerical modeling. His professional goal is to participate in research interdisciplinary teams and incorporate the role of applied physics in the understanding and protection of pristine ecosystem such as the Patagonia.Oscar joined the EDCE doctoral program at EPFL, in 2016 and works in the Aquatic Physics Systems Laboratory- APHYS. In order to complete his Ph.D., Oscar participates in the SNF-Sinergia project entitled: “High- Resolution Sensing of Aquatic Ecosystems with a Fleet of Small Underwater Robots”.',
        'DIFFUSION'     : 'Diffusion',
        'NAME_DIFFUSION': 'Daisy Lucas',
        'BIO_DIFFUSION' : 'Daisy Lucas. Ms Lucas is a Civil engineer graduated from University of Chile, with expertise in soil dynamics and natural hazards. She did her Masters in Rensselaer Polytechnic Institute in geotechnical earthquake engineering and is currently doing her Phd in slope stability at ETH Zurich. She has worked in infrastructure in USA, Chile and in mining projects in the Caribbean.',
        'NAME_DIFFUSION2': 'Jutta Bürgi',
        'BIO_DIFFUSION2' :'Jutta is a Sociologist who graduated from University of Chile and she also holds a Master’s Degree in Sociology and Political Sciences at Zurich University. Her principal area of interest is the Sociology of Education. In Chile, she worked in this field at the Interuniversity Centre for Development (CINDA) and in the Consulting Firm VERDE, which advises – among other legal entities – the Chilean Government in educational and scientific policies. At the moment she is doing an internship as a research assistant at the Education Systems Research Division of the KOF Swiss Economic Institute of ETH Zurich.She wrote her Master thesis on the determinants of educational inequality at the tertiary level of the Swiss and German educational systems in the context of educational expansion during the second half of the 20th century.Jutta was born in Switzerland, but she lived in Chile for almost 8 years, so she knows both countries quite well. She is strongly interested in continuing to develop her professional career in the field of educational and scientific policies, as well as in Sociology of Education in general and in contributing to both countries from this emerging field of study’s point of view.',
        'NAME_DIFFUSION3': 'Waldo Valenzuela',
        'BIO_DIFFUSION3' : 'Waldo Valenzuela is from Los Angeles, Bio-Bio region. He studied Electronic Engineering at the University of Concepcion, where he also obtained a Master of Science with specialization in mixed-signal design of VLSI circuits, and neural networks. After, he worked as group head in a FONDEF project, and as part-time professor at the same University in Biomedical Engineering area. His research area focuses on medical software design oriented to clinical application and medical diagnosis.Since 2012 is living in Switzerland where he obtained his Ph.D in Biomedical Engineering at University of Bern. From September 2016 is doing his Post-Doctoral research project between the University of Bern and University Hospital of Bern. His doctoral thesis together with his work at the University of Concepcion, and his Post-Doctoral research are focused on improving three-dimensional segmentation algorithms, which could be used in a clinical environment. Specifically, the development of auto- and semi-automatic correction techniques, which goal is improving the quality of the segmentation algorithm by minimizing and optimizing the information provided by the user.',
        'NAME_DIFFUSION4': 'Carolina Zielke',
        'BIO_DIFFUSION4' : 'Carolina is Industrial Engineer of the Technical Federico Santa Maria University of Chile. She worked in Operation Research at the Chilean Navy. Carolina did a Master of Advanced Studies in Energy System with emphasis in Renewable Energies at the University of Applied Science of Technology NTB Buchs of Switzerland and a Master of Advanced Studies in Energy Economy at the University of Applied Sciences HTW Chur of Switzerland. Carolina is working since 2011 in an electrical distribution company of the canton Zurich, in the area of electrical grid economies. Carolina is married and has two daughters.',
        'NAME_DIFFUSION5'   : 'Alvaro Rodriguez',
        'BIO_DIFFUSION5'    : 'Bio',
        'NAME_DIFFUSION6'   : 'Agustin Cautin',
        'BIO_DIFFUSION6'    : 'Bio',
        'COMMUNICATIONS'    : 'Communications',
        'NAME_ COMMUNICATIONS'  : 'Rodrigo Polanco',
        'BIO_COMMUNICATIONS'    : 'Rodrigo is an Assistant Professor of Economic Law at the University of Chile where he has been teaching investment law and international trade law, both at the Institute of International Studies and the Faculty of Law, where he also served as the Director of International Affairs.He holds a Bachelor and a Master of Laws from University of Chile School of Law, and an LL.M. in International Legal Studies from New York University School of Law. In February 2013, Rodrigo joined the World Trade Institute at the University of Bern as a Ph.D fellow and as a researcher/lecturer in international investment law, under the SECO Project. He is also visiting professor at Universidad Externado of Colombia and the Pontifical Catholic University of Peru, and co-founder of Fiscalía del Medio Ambiente (FIMA) a Chilean environmental NGO where he serves as Director of their environmental law journal (Justicia Ambiental).Rodrigo is married with two children, and currently lives in Bern.',
        'TITLE_EX_DIRECTIVE': 'Ex Directive',
        'EX_PRESIDENCY'     : 'Presidency',
        'NAME_EX_PRESIDENT' : 'Lorenzo Reyes',
        'BIO_EX_PRESIDENT'  : 'Lorenzo Reyes-Chamorro was born in Santiago, Chile, on September 8, 1984. He received the B.Sc. degree in Electrical Engineering in 2007 and the professional diploma on Electrical Engineer in 2009 from the University of Chile.From 2009 to 2012 he worked as a Researcher in the Energy Center of the Physical and Mathematical Sciences Faculty in University of Chile,first as a project engineer but then leading the project ESUSCON which had as goal the transformation of Huatacondo (North of Chile) to become the first energetically self-sustainable village in Latin America. During that time he was also Invited Professor in several subjects in the Department of Electrical Engineering, being part of the review committee of various candidates to the Electrical Engineer diploma.Since January 2013, he has been working toward the Ph.D. degree at the Distributed Electrical System Laboratory (DESL), Swiss Federal Institute of Technology of Lausanne (EPFL), Switzerland.Lorenzo is married with 1 child. They currently live in Lausanne.',
        'NAME_EX_DIFFUSION': 'Carolina Zielke',
        'BIO_EX_DIFFUSION' : 'Carolina is Industrial Engineer of the Technical Federico Santa Maria University of Chile. She worked in Operation Research at the Chilean Navy. Carolina did a Master of Advanced Studies in Energy System with emphasis in Renewable Energies at the University of Applied Science of Technology NTB Buchs of Switzerland and a Master of Advanced Studies in Energy Economy at the University of Applied Sciences HTW Chur of Switzerland. Carolina is working since 2011 in an electrical distribution company of the canton Zurich, in the area of electrical grid economies. Carolina is married and has two daughters.',
        'NAME_EX_DIFFUSION2': 'Daisy Lucas',
        'BIO_EX_DIFFUSION2' : 'Daisy Lucas. Ms Lucas is a Civil engineer graduated from University of Chile, with expertise in soil dynamics and natural hazards. She did her Masters in Rensselaer Polytechnic Institute in geotechnical earthquake engineering and is currently doing her Phd in slope stability at ETH Zurich. She has worked in infrastructure in USA, Chile and in mining projects in the Caribbean.',
        'NAME_EX_DIFFUSION3': 'Macarena Garcia',
        'BIO_EX_DIFFUSION3' :'Macarena García González. Cultural Anthropologist of University of Zurich. After finishing a degree in Communication Studies and Journalism, Macarena worked as a journalist for 8 years at the cultural supplement of El Mercurio newspaper, in Chile. She is co-author, with Óscar Contardo, of La Era Ochentera. Tevé, pop y under en el Chile de los 80 (Ediciones B, 2005), a book on culture and society during Augusto Pinochet’s dictatorship.In 2008, she obtained a grant by the Chilean government for a MA in Cultural Studies at University of Maastricht, The Netherlands. Macarena graduated in 2010 obtaining the prize to the best thesis of the faculty of Social Studies and Arts and was hired as a researcher by the university as a fellow of the Attracting and Coaching Talent program. In 2011, Macarena began her doctoral dissertation at the University of Zurich, Switzerland, in the department of Social Anthropology and Cultural Studies (ISEK). Her project has been supported by the Swiss National Science Foundation. She lectures at this department and at the University of Lichtenstein. Macarena is married and has one child.',
        'NAME_EX_DIFFUSION4': 'Evelyn Avilés',
        'BIO_EX_DIFFUSION4' : 'Evelyn was born in Angol (Chile) in 1983. Evelyn holds a “Licenciado” in Biochemistry degree, obtained at the University of Concepcion, Chile in 2007. At the same university, she did her Masters in Biochemistry and Bioinformatics. Her Masters thesis dealt with the role of the Wnt signaling pathway in the formation of vertebrate synapses (neuromuscular junction) during embryonic development. Shortly after, Evelyn started her PhD at the University of Zurich partially funded by a “Becas Chile” grant. In September 2014, Evelyn successfully defended her PhD thesis in Neurocience, entitled “A Wnt signaling network is required for commissural axon guidance” in the field of Developmental Neurobiology under the supervision of Dr. Esther Stoeckli. At present, Evelyn continues to do research in Dr. Stoeckli´s laboratory, while she applies for Post-doc positions to start soon.Evelyn is married and has a child. She currently lives in Zurich.',
        'NAME_ EX_COMMUNICATIONS'  : 'Rodrigo Polanco',
        'BIO_EX_COMMUNICATIONS'    : 'Rodrigo is an Assistant Professor of Economic Law at the University of Chile where he has been teaching investment law and international trade law, both at the Institute of International Studies and the Faculty of Law, where he also served as the Director of International Affairs.He holds a Bachelor and a Master of Laws from University of Chile School of Law, and an LL.M. in International Legal Studies from New York University School of Law. In February 2013, Rodrigo joined the World Trade Institute at the University of Bern as a Ph.D fellow and as a researcher/lecturer in international investment law, under the SECO Project. He is also visiting professor at Universidad Externado of Colombia and the Pontifical Catholic University of Peru, and co-founder of Fiscalía del Medio Ambiente (FIMA) a Chilean environmental NGO where he serves as Director of their environmental law journal (Justicia Ambiental).Rodrigo is married with two children, and currently lives in Bern.',
        'NAME_EX_FINANCES':'Felipe Orellana',
        'BIO_EX_FINANCES' : 'Felipe (October, 1985) was born in San Fernando, in the heart of the Colchagua Valley, O’Higgins Region, Chile. He is a Mining Engineer and holds a Master degree in Underground Mining from Universidad de Chile (2012).He was granted with the Anglo American Scholarship (2008-2010) of the Department of Mining Engineering. He was Vice-president (2008) and President (2009) of the Mining Student Association. He also worked at the Advanced Mining Technology Centre (AMTC) in the research group for mining design. His Masters thesis tackled the impact of a new ore extraction technology for massive underground mining. Before coming to Switzerland, he worked at HATCH Engineering and IM2 Codelco, and was involved in CODELCO and Rio Tinto projects.Felipe holds an adjunct professor position at the Mining Engineering Department at the Universidad de Chile. He is currently working on his doctoral studies at the Laboratory of Rocks Mechanics – EPFL, Lausanne, Switzerland. His main interests are rock mechanics, mining, tunnelling and engineering geology.',
        'NAME_EX_FINANCES2': 'Alvaro Ayala',
        'BIO_EX_FINANCES2' : 'Alvaro is a civil engineer and master in Resources and the Water Environment of Universidad de Chile. In this university, he worked as an engineer and researcher in different projects related to mountain hydrology, climate change and water resources management. Currently, he holds a Becas Chile scholarship and he is a PhD candidate in the ETH-Zurich group of Hydrology and Water Resources Management. In this group, he continues his research on hydrological processes of mountainous regions, with special focus in the Andes.Alvaro lives in Zurich since 2012 and he takes part of a constant scientific collaboration between glaciology and hydrology researchers of Switzerland and Chile.',
        'CONTINUE': 'Continue',
        'TITLE_BUZON': 'Buzón Académico y Universitario',
        'DESC_SUMMARY_BUZON': 'The «Buzón Universitario» of PL was created 7 years ago with the directives between 2008 and 2014: Julie Bauer (Suiza, UNI GE), José Parra ...',
        'TITLE_PAPAYAPODS': 'papayapods helps you to find a new home',
        'DESC_SUMMARY_PAPAYAPODS': 'All of us have at some point of our lives rented an apartment after moving to a new city, this can be an stressful experience, ...', 
        'TITLE_TRUMP': 'Our Director Dr. Rodrigo Polanco gives his vision on the recent election of Donald Trump in the United States',
        'DESC_SUMMARY_TRUMP': 'What does a Trump presidency mean for the developing world? After an 18-month campaign characterised by inward-looking nationalism and often racist vitriol, the idea that ...',
        'TITLE_ENCUENTRO_2016': 'Encuentro Ginebra 2016',
        'DESC_SUMMARY_ENCUENTRO_2016': 'El pasado 7 de mayo, en la Universidad de Ginebra, la Asociación de investigadores chilenos en Suiza (ICES) realizó su Encuentro 2016....',
        'TITLE_REGISTRO_CHILENOS': 'Segundo registro de chilenos que viven en el extranjero',
        'DESC_SUMMARY_REGISTRO_CHILENOS': 'El Instituto Nacional de Estadísticas junto al Ministerio de Relaciones Exteriores actualmente están llevando a cabo el “Segundo Registro de Chilenos en el Exterior...',
        'TITLE_AVISO_ENCUENTRO_2016': 'Save the date! ICES second meeting will take place in Geneva next 7th of May',
        'DESC_SUMMARY_AVISO_ENCUENTRO': 'This year the event will take place on Saturday May 7, 2016 from 10:00 to 19:30 at the University of Geneva. The meeting will be held under ...',
        'TITLE_CHILE_GLOBAL': 'Presentando a ICES en Encuentros ChileGlobal 2015',
        'DESC_CHILE_GLOBAL': 'El evento titulado: “Developing sustainable futures”, fue llevado a cabo, bajo la temática general del desarrollo de un futuro sustentable para Chile, como también para ...',
        'TITLE_CONSTRUYENDO_PUENTES': 'Primer Encuentro ICES: “Construyendo Puentes”',
        'DESC_CONSTRUYENDO_PUENTES': 'Todo un éxito resultó el primer evento de la asociación de Investigadores Chilenos en Suiza (ICES), para abordar el rol de la investigación científica y ...',
        'TITLE_ENCUENTRO_GLOBAL_2015': 'Encuentros ChileGlobal 2015',
        'DESC_ENCUENTRO_GLOBAL': 'Gran noticia desde Encuentros ChileGlobal 2015 Las Conferencias Encuentros son reuniones de ciencia y emprendimiento que congregan a investigadores y líderes de opinión, chilenos y extranjeros, ...',
        'TITLE_CREACION_ICES': 'Se crea oficialmente la Asociación de Investigadores Chilenos en Suiza – ICES',
        'DESC_CREACION_ICES' :'En Lausanne Cantón de Vaud, con no más de 2ºC de temperatura, se llevó a cabo la ceremonia simbólica de la Asamblea Constitutiva  de ICES ...',
        'TITLE_ETH_APOYO': 'ETH Global apoyará a ICES en nuestras primeras actividades',
        'DESC_ETH_APOYO': 'ETH Global – “La oficina internacional de ETH Zurich” – es la oficina responsable de implementar estrategias de desarrollo y colaboración global para ETH Zurich. ...',
        'TITLE_ICES_EMBAJADOR': 'Reunión de ICES con el embajador de Chile en Suiza',
        'DESC_ICES_EMBAJADOR': 'A partir de la amable invitación hecha por el embajador de Chile en Suiza, el Sr. José Luis Balmaceda y gracias a la coordinación por ...',
        'TITLE_BERNA_2014': 'En Berna se realiza la primera reunión de la asociación',
        'DESC_BERNA_2014': 'Coincidiendo con el espíritu pratiótico de la temporada, el 18 de septiembre de 2014 se reunió parte de quienes conformarían la directiva de la asociación ...',
        'TITLE_ENCUENTRO_2017': 'Encuentro 2017 ICES en Berna',
        'DESC_ENCUENTRO_2017':'El evento se llevará a cabo el Sábado 20 de Mayo del 2017 de 09:00 a 17:00 horas en el Casino Kursaal Bern, Kornhausstrasse 3, 3000 Bern...'
    });

    $translateProvider.translations('es', {
        'MENU_HOME': 'HOME',
        'MENU_ABOUT': 'QUIENES SOMOS',
        'MENU_MOTIVATION': 'Motivacion',
        'MENU_GOAL': 'Objetivos de la asociacion',
        'MENU_ORG': 'Organizacion',
        'MENU_DIRECTIVE': 'Directiva',
        'MENU_EXDIRECTIVE':'Directiva 2015-2016',
        'MENU_STUDY': 'ESTUDIA EN SUIZA',
        'MENU_ICES': 'COMUNIDAD ICES',
        'MENU_REQUIRIMENTS': 'Requisitos',
        'MENU_BENEFITS': 'Beneficios de ser miembro',
        'MENU_MEMBERSHIP':'Membresia anual',
        'MENU_SIGN_IN': 'Formulario de registro',
        'MENU_EVENT': 'EVENTOS',
        'MENU_NEWS': 'NOTICIAS',
        'MENU_PHOTO': 'FOTOS',
        'MENU_CONTACT': 'CONTACTO',
        'FOOTER_CONTACT_US': 'Contactanos',
        'FOOTER_PARTNER':'Colaboradores / Socios',
        'TITLE_ABOUT': 'Quienes Somos?',
        'TITLE_MOTIVATION': 'Que motiva a ICES',
        'TITLE_GOAL': 'Objetivos de la asociación',
        'TITLE_PPAL_GOAL': 'Estos son nuestros principales objetivos',
        'TITLE_ORG': 'Organización',
        'TITLE_OUR_ORG': 'Nuestra Organización',
        'TITLE_DIRECTIVE':'Directiva',
        'TITLE_NEWS' : 'Noticias recientes',
        'CONTACT_TEXT' : 'Por favor complete el siguiente formulario. Le responderemos a la brevedad.',
        'NAME_CONTACT': 'Nombre',
        'MAIL_CONTACT' : 'Mail',
        'SUBJECT_CONTACT': 'Asunto',
        'MESSAGE_CONTACT': 'Mensaje',
        'SUBMIT_CONTACT' : 'Enviar',
        'MAIN_TITLE_INDEX': 'ICES',
        'CAROUSEL_TEXT': 'ICES esta conformada por investigadores, academicos, estudiantes y profesionales que trabajan en Suiza',
        'CAROUSEL_TEXT2': 'ICES se interesa en la colaboracion Chileno-Suiza en investigacion',
        'ABOUT_US': 'ICES (Investigadores Chilenos en Suiza) es una asociación sin fines de lucro conformada por un grupo de investigadores, académicos, estudiantes y profesionales que desarrollan sus respectivas actividades en Suiza, interesados en aportar a la colaboración chileno-suiza en todas las áreas de la investigación y el conocimiento.',
        'MOTIVATION': 'ICES busca ser un aporte a la colaboración académica y profesional entre Chile y Suiza. Basados en nuestras experiencias académicas y profesionales en Suiza, creemos que existe un amplio espacio para la colaboración científica y profesional entre personas e instituciones suizas y chilenas. Creemos que la vida académica, profesional e incluso personal de los investigadores chilenos en Suiza se puede beneficiar de los consejos y experiencias pasadas de chilenos que ya se encuentran trabajando en Suiza. Nuestra motivación principal es crear un espacio donde los investigadores chilenos desempeñándose en Suiza puedan contactarse, intercambiar experiencias y explorar nuevos desafíos académicos junto a organizaciones chilenas y suizas, así como también ser una plataforma de información para facilitar el intercambio de estudiantes chilenos en Suiza.',
        'GOAL': 'Los objetivos de la asociación se dividen en tres niveles, los que van desde objetivos de corto plazo en el primer nivel hasta objetivos de largo plazo en el tercero:',
        'GOAL_LEVEL1': 'Nivel 1: Apoyar a investigadores chilenos durante toda su estadía en Suiza.',
        'GOAL_LIST1_LEVEL1': 'Crear una plataforma de información para investigadores y estudiantes en Chile interesados en Suiza en busca de oportunidades académicas y profesionales.',
        'GOAL_LIST2_LEVEL1': 'Facilitar la integración de nuevos investigadores y estudiantes chilenos en Suiza.',
        'GOAL_LIST3_LEVEL1': 'Fortalecer los lazos académicos y científicos entre investigadores, académicos, estudiantes y profesionales chilenos viviendo en Suiza.',
        'GOAL_LEVEL2': 'Nivel 2: Promover la colaboración científica y profesional entre personas e instituciones chilenas y suizas.',
        'GOAL_LIST1_LEVEL2': 'Crear una plataforma donde investigadores y estudiantes chilenos y suizos compartan información, resuelvan dudas y encuentren socios de colaboración u oportunidades laborales en ambos países.',
        'GOAL_LIST2_LEVEL2': 'Incentivar el desarrollo de proyectos e iniciativas científicas y académicas en ambos países.Mostrar Chile en Suiza como una valiosa oportunidad para la cooperación científica.',
        'GOAL_LIST3_LEVEL2':' Mostrar Chile en Suiza como una valiosa oportunidad para la cooperación científica.',
        'GOAL_LEVEL3': 'Nivel 3: Participar en la discusión sobre el desarrollo científico y académico en Chile.',
        'GOAL_LIST1_LEVEL3': 'Participar y colaborar con distintas asociaciones y redes de investigadores chilenos en el extranjero.',
        'GOAL_LIST2_LEVEL3': 'Contribuir desde nuestra experiencia al desarrollo de políticas para la reintegración de investigadores y estudiantes que vuelven a Chile. En particular, buscamos ayudar a los estudiantes que participan del programa Becas Chile.',
        'STRUCTURE':'Los órganos de la asociación son:',
        'STRUCTURE_LIST1': 'La asamblea general',
        'STRUCTURE_LIST2': 'El órgano financiero y administrativo',
        'STRUCTURE_LIST3': 'El órgano encargado de la difusión la Directiva',
        'STRUCTURE_LIST4': 'La directiva a borde',
        'SHOW_BIO': 'Mostrar biografía',
        'HIDE_BIO': 'Ocultar biografía',
        'PRESIDENCY'     : 'Presidencia',
        'NAME_PRESIDENT' : 'Lorenzo Reyes',
        'BIO_PRESIDENT'    : 'Lorenzo Reyes nació en Santiago de Chile el 8 de septiembre de 1984. Recibió su grado de Licenciado en Ciencias de la Ingeniería Eléctrica en 2007 y su título profesional de Ingeniero Civil Electricista en 2009 en la Universidad de Chile.Entre el 2009 y el 2012 se desempeñó como Investigador en el Centro de Energía de la Facultad de Ciencias Físicas y Matemáticas de la misma Universidad, primero como ingeniero de proyecto y luego como líder del proyecto ESUSCON para transformar a Huatacondo (Norte de Chile) en el primer pueblo energéticamente autosustentable de Latinoamérica. Durante ese tiempo se desempeñó también como Profesor Invitado en diversas materias en el Departamento de Ingeniería Eléctrica, siendo parte de la comisión examinadora de varios candidatos al título de Ingeniero Civil Electricista.Desde Enero 2013 es estudiante de doctorado en el Laboratorio de Sistemas Eléctricos Distribuidos en la Escuela Federal Politécnica de Lausanne, Suiza.Lorenzo está casado y tiene 1 pequeño hijo. Actualmente viven en Lausanne.',
        'SECRETARY' : 'Secretario',
        'NAME_SECRETARY': 'Felipe Orellana',
        'BIO_SECRETARY' : 'Felipe (Octubre, 1985) es oriundo de San Fernando, pleno valle de Colchagua en la Región de O’Higgins, Chile. Es Ingeniero Civil de Minas y Magister en Minería, ambos grados obtenidos en la Universidad de Chile (2012). Obtuvo la beca Anglo American del Departamento de Ingeniería de Minas (2008 – 2010) durante sus estudios de pregrado. Fue vicepresidente (2008) y Presidente (2009) del Centro de Alumnos de la carrera. Su tesis de Magister la realizó al alero del Centro Avanzado de Tecnología para la Minería (AMTC) de la Facultad de Ciencias Físicas y Matemáticas, donde abordó el desarrollo de una nueva tecnología de extracción de mineral en el área de minería masiva subterránea. Antes de partir a Suiza, trabajó en Hatch Ingeniería y en IM2 de Codelco, en proyectos de Codelco y Rio Tinto.Felipe es parte del Dpto. de Ingeniería de Minas de la Universidad de Chile como profesor adjunto. Actualmente está trabajando en su doctorado en el Laboratorio de Mecánica de Rocas de EPFL. Sus temas de interés están relacionados con mecánica de rocas, minería , túneles e ingeniería geologica.',
        'NAME_SECRETARY2': 'Joaquín Bastías',
        'BIO_SECRETARY2': 'Joaquín Bastías es oriundo de Puente Alto, Santiago. Cursó estudios de geología en la Universidad de Chile, después de trabajar en la industria un par de años realizó estudios de Master en la misma casa de estudios. Su área de investigación está enfocada en la evolución tectónica y termal de la Península Antártica, en donde ha realizado diversas campañas de terreno y colaborado con diversas instituciones en Chile y el extranjero.Se encuentra en Suiza desde el 2015 realizando sus estudios de doctorado en Ciencias de la Tierra en la Universidad de Ginebra. Su tesis, al igual que sus trabajos en la Universidad de Chile, se enfoca en temáticas que comprenden la geocronología, geoquímica y termocronología.',
        'TREASURER': 'Treasurer',
        'NAME:TREASURER': 'Oscar Sepúlveda',
        'BIO_TREASURER':'Oscar Sepúlveda Steiner nació en Santiago, Chile, el 28 de mayo de 1989. Él es un Ingeniero Civil de la Universidad de Chile y tiene un Magíster en Recursos Hídricos y Medio Ambiente, de la misma casa de estudios. Obtuvo la beca Nacional de Magister de CONICYT para el periodo 2013-2014. Sus temas de interés son la fluidodinámica ambiental y los procesos de transporte de masa en sistema acuáticos. Su foco principal es desarrollar investigación en limnología física (física de los lagos) basada en mediciones de terreno y modelación numérica. La meta profesional de Oscar es participar en equipos interdisciplinarios de investigación incorporando el rol de la física aplicada en el entendimiento y protección de ecosistemas prístinos como la Patagonia. Oscar se incorporó al programa doctoral EDCE de la EPFL en 2016 y trabaja en el Laboratorio de Física de Sistemas Acuáticos – APHYS. Para completar su doctorado, Oscar participa en el proyecto SNF-Sinergia titulado: “Detección de Alta Resolución, en Ecosistemas Acuáticos, mediante el uso de una Flota de Pequeños Robots Sumergibles”.',
        'DIFFUSION': 'Diffusion',
        'NAME_DIFFUSION': 'Daisy Lucas',
        'BIO_DIFFUSION': 'Daisy Lucas ingeniero civil graduada en la Universidad de Chile. Su especialidad es la dinámica de suelos y estabilidad de taludes. Realizó sus estudios de masters en Rensselaer Polytechnic Institute en ingeniería geotécnica desarrollando simulaciones de licuación de suelos durante terremotos, y actualmente se encuentra realizando sus estudios de doctorado en ETH Zurich en monitoreo y modelación fisica de aludes. Su experiencia laboral cuenta con proyectos de infraesturctura en Estados Unidos, puentes en Chile, y proyectos mineros en el Caribe.',
        'NAME_DIFFUSION2' : 'Jutta Bürgi',
        'BIO_DIFFUSION2'  : 'Jutta es Socióloga de la Universidad de Chile y Magíster en Sociología y Ciencias Políticas de la Universidad de Zurich. Su interés principal es la Sociología de la Educación. En Chile, ella trabajó en esta área en el Centro Interuniversitario de Desarrollo (CINDA) y en la Consultora VERDE, que asesora, entre otras entidades, al Estado Chileno en temas de política educacional y científica. Actualmente esta realizando una práctica profesional como asistente de investiagación de la Division de Investigación en Systemas de Educación del Instituto Económico Suizo KOF de la ETH Zürich. Su tesis de Magíster la escribió acerca de los determinantes de la inequidad educacional a nivel terciario de los sistemas educacionales Suizo y Alemán en el contexto de la expansion educacional a lo largo de la segunda mitad del siglo XX. Jutta nació en Suiza, viviendo luego por casi 8 años en Chile, por lo que conoce bastante bien ambos países. Se interesa mucho en seguir desarrollando su carrera profesional en el ámbito de las políticas educacionales y de ciencia, así como en la Sociología de la Educación en general, para lograr contribuir a ambos países desde el punto de vista de este emergente campo de estudio.',
        'NAME_DIFFUSION3': 'Waldo Valenzuela',
        'BIO_DIFFUSION3' : 'Waldo Valenzuela es oriundo de Los Angeles, Región del Bio-Bio. Cursó estudios de Ingeniería Civil Electrónica en la Universidad de Concepción, donde además obtuvo su Master en Ciencias con especialización en diseño mixto de VLSI y redes neuronales. Posteriormente se desempeñó como jefe de un proyecto FONDEF, y como docente part-time en la misma universidad en el área de Ingeniera Biomédica. Su área de investigación está enfocada en diseño de software médico orientado a aplicaciones clínicas y diagnóstico. Se encuentra en Suiza desde el 2012 donde realizó sus estudios de doctorado en Ingeniería Biomédica en la Universidad de Berna. Desde septiembre del 2016, se encuentra realizado un Post-Doctorado conjunto entre la Universidad de Berna y el Hospital Universidad de la ciudad de Berna. Su tesis doctoral, junto con sus trabajos en la Universidad de Concepción, y su actual Post-Doctorado, se enfocan en temáticas que comprenden mejorar la calidad de los algoritmos de segmentación tridimensionales, de tal manera que estos puedan ser utilizados en el ambiente clínico. Específicamente, el desarrollo de herramientas de corrección automáticas y semiautomática, las cuales minimizan y optimizan la información proporcionada por el usuario con el fin de reducir el tiempo de corrección y mejorar la calidad de los resultados de segmentación.',
        'NAME_DIFFUSION4' : 'Carolina Zielke',
        'BIO_DIFFUSION4'  : 'Carolina es Ingeniero Civil Industrial de la Universidad Técnica Federico Santa María en Chile. Se desempeñó en el área de Operation Research en la Armada de Chile. Carolina realizó un Master of Advanced Studies en Sistemas Energéticos con énfasis en Energías Renovables, en la Universidad de Ciencias Aplicadas en Tecnología NTB Buchs en Suiza y un Master of Advanced Studies en Economía Energética en la Universidad de Ciencias Aplicadas HTW Chur en Suiza. Carolina trabaja desde el año 2011 en una Empresa Distribuidora Eléctrica del Cantón Zúrich, en el área de Economía de Redes Eléctricas. Carolina está casada y tiene dos hijas.',
        'NAME_DIFFUSION5': 'Alvaro Rodriguez',
        'BIO_DIFFUSION5' : 'Bio',
        'NAME_DIFFUSION6': 'Agustin Cautin',
        'BIO_DIFFUSION6' : 'Bio',
        'COMMUNICATIONS'        : 'Communications',
        'NAME_ COMMUNICATIONS'  : 'Rodrigo Polanco',
        'BIO_COMMUNICATIONS'    : 'Rodrigo es profesor asistente de Derecho Económico de la Universidad de Chile, donde ha estado enseñando derecho de inversiones y derecho internacional económico, tanto en el Instituto de Estudios Internacionales y la Facultad de Derecho, donde también se desempeñó como Director de Asuntos Internacionales. Rodrigo tiene una licenciatura y una maestría en Derecho de la Universidad de Chile y un LL.M. en Estudios Legales Internacionales de la Facultad de Derecho de la Universidad de Nueva York. En febrero de 2013, Rodrigo se unió al World Trade Institute de la Universidad de Berna como becario de doctorado y como investigador / instructor de derecho internacional de inversiones, en el marco del Proyecto SECO. También es profesor visitante en la Universidad Externado de Colombia y la Pontificia Universidad Católica del Perú, y co-fundador de la Fiscalía del Medio Ambiente (FIMA) una ONG ambiental chilena, donde se desempeña como director de la devista de derecho ambiental “Justicia Ambiental”. Rodrigo está casado y tiene dos hijos, y actualmente vive en Berna.',
        'TITLE_EX_DIRECTIVE': 'Ex Directiva',
        'EX_PRESIDENCY'     : 'Presidencia',
        'NAME_EX_PRESIDENT' : 'Lorenzo Reyes',
        'BIO_EX_PRESIDENT'    : 'Lorenzo Reyes nació en Santiago de Chile el 8 de septiembre de 1984. Recibió su grado de Licenciado en Ciencias de la Ingeniería Eléctrica en 2007 y su título profesional de Ingeniero Civil Electricista en 2009 en la Universidad de Chile.Entre el 2009 y el 2012 se desempeñó como Investigador en el Centro de Energía de la Facultad de Ciencias Físicas y Matemáticas de la misma Universidad, primero como ingeniero de proyecto y luego como líder del proyecto ESUSCON para transformar a Huatacondo (Norte de Chile) en el primer pueblo energéticamente autosustentable de Latinoamérica. Durante ese tiempo se desempeñó también como Profesor Invitado en diversas materias en el Departamento de Ingeniería Eléctrica, siendo parte de la comisión examinadora de varios candidatos al título de Ingeniero Civil Electricista.Desde Enero 2013 es estudiante de doctorado en el Laboratorio de Sistemas Eléctricos Distribuidos en la Escuela Federal Politécnica de Lausanne, Suiza.Lorenzo está casado y tiene 1 pequeño hijo. Actualmente viven en Lausanne.',
        'NAME_EX_DIFFUSION' : 'Carolina Zielke',
        'BIO_EX_DIFFUSION'  : 'Carolina es Ingeniero Civil Industrial de la Universidad Técnica Federico Santa María en Chile. Se desempeñó en el área de Operation Research en la Armada de Chile. Carolina realizó un Master of Advanced Studies en Sistemas Energéticos con énfasis en Energías Renovables, en la Universidad de Ciencias Aplicadas en Tecnología NTB Buchs en Suiza y un Master of Advanced Studies en Economía Energética en la Universidad de Ciencias Aplicadas HTW Chur en Suiza. Carolina trabaja desde el año 2011 en una Empresa Distribuidora Eléctrica del Cantón Zúrich, en el área de Economía de Redes Eléctricas. Carolina está casada y tiene dos hijas.',
        'NAME_EX_DIFFUSION2': 'Daisy Lucas',
        'BIO_EX_DIFFUSION2': 'Daisy Lucas ingeniero civil graduada en la Universidad de Chile. Su especialidad es la dinámica de suelos y estabilidad de taludes. Realizó sus estudios de masters en Rensselaer Polytechnic Institute en ingeniería geotécnica desarrollando simulaciones de licuación de suelos durante terremotos, y actualmente se encuentra realizando sus estudios de doctorado en ETH Zurich en monitoreo y modelación fisica de aludes. Su experiencia laboral cuenta con proyectos de infraesturctura en Estados Unidos, puentes en Chile, y proyectos mineros en el Caribe.',
        'NAME_EX_DIFFUSION3': 'Macarena García',
        'BIO_EX_DIFFUSION3' : 'Macarena García González. Periodista de la Universidad Católica. Antropóloga cultural de la Universidad de Zúrich.Después de estudiar Periodismo en la Universidad Católica, Macarena trabajó por ocho años para el suplemento Artes y Letras del diario El Mercurio. Es también co-autora, junto a Óscar Contardo, de La Era Ochentera. Tevé, pop y under en el Chile de los 80 (Ediciones B, 2005), un libro sobre cultura y sociedad durante la dictadura de Pinochet que cuenta ya con tres ediciones.En 2008 obtuvo una beca del gobierno chileno para realizar un magíster en estudios culturales en la Universidad de Maastricht, Holanda. Macarena se graduó en 2010 obteniendo el premio a la mejor tesis de la Facultad de Ciencias Sociales y Artes y fue contratada como investigadora en la universidad como parte deel programa Attracting and Coaching Talent. En 2011, Macarena inició su investigación doctoral en la Universidad de Zúrich, Suiza, en el departamento de Antropología Social y Estudios Culturales (ISEK). Su proyecto ha sido apoyado por el Fondo Nacional Científico Suizo. Da clases en la Universidad de Zúrich y en la Universidad de Lichtenstein.Macarena está casada y tiene un hijo.',
        'NAME_EX_DIFFUSION4' : 'Evelyn Aviles',
        'BIO_EX_DIFFUSION4'  : 'Evelyn nació en Angol (Chile) en el año 1983. Evelyn obtuvo el grado de Licenciado en Bioquímica en marzo del año 2007, otorgado por la Universidad de Concepción, Chile. En la misma casa univeristaria, en el año 2009 obtuvo el grado de Magíster en Bioquímica y Bioinformática. Su tesis de Magíster consistió en la investigación del rol de la vía de señalización Wnt en la formación de la unión neuromuscular de vertebrados. Al poco tiempo, Evelyn comenzó sus estudios de doctorado en la Universidad de Zurich con financiamiento de Becas Chile. En septiembre de 2014, Evelyn defendió con éxito sus tesis de doctorado en Neurociencia titulada “A Wnt signaling network is required for commissural axon guidance”, en el area de la neurobiología del desarrollo, bajo la supervisión de la Dra. Esther Stoeckli. Actualmente, Evelyn continúa hacienda investigación en el laboratorio de la Dra. Stoeckli, al mismo tiempo que postula a post-doctorados para comenzar en el corto plazo.Evelyn está casada y tiene un hijo. Actualmente vive en Zurich.',
        'NAME_ EX_COMMUNICATIONS'  : 'Rodrigo Polanco',
        'BIO_EX_COMMUNICATIONS'    : 'Rodrigo es profesor asistente de Derecho Económico de la Universidad de Chile, donde ha estado enseñando derecho de inversiones y derecho internacional económico, tanto en el Instituto de Estudios Internacionales y la Facultad de Derecho, donde también se desempeñó como Director de Asuntos Internacionales. Rodrigo tiene una licenciatura y una maestría en Derecho de la Universidad de Chile y un LL.M. en Estudios Legales Internacionales de la Facultad de Derecho de la Universidad de Nueva York. En febrero de 2013, Rodrigo se unió al World Trade Institute de la Universidad de Berna como becario de doctorado y como investigador / instructor de derecho internacional de inversiones, en el marco del Proyecto SECO. También es profesor visitante en la Universidad Externado de Colombia y la Pontificia Universidad Católica del Perú, y co-fundador de la Fiscalía del Medio Ambiente (FIMA) una ONG ambiental chilena, donde se desempeña como director de la devista de derecho ambiental “Justicia Ambiental”. Rodrigo está casado y tiene dos hijos, y actualmente vive en Berna.',
        'NAME_EX_FINANCES': 'Felipe Orellana',
        'BIO_EX_FINANCES' : 'Felipe (Octubre, 1985) es oriundo de San Fernando, pleno valle de Colchagua en la Región de O’Higgins, Chile. Es Ingeniero Civil de Minas y Magister en Minería, ambos grados obtenidos en la Universidad de Chile (2012). Obtuvo la beca Anglo American del Departamento de Ingeniería de Minas (2008 – 2010) durante sus estudios de pregrado. Fue vicepresidente (2008) y Presidente (2009) del Centro de Alumnos de la carrera. Su tesis de Magister la realizó al alero del Centro Avanzado de Tecnología para la Minería (AMTC) de la Facultad de Ciencias Físicas y Matemáticas, donde abordó el desarrollo de una nueva tecnología de extracción de mineral en el área de minería masiva subterránea. Antes de partir a Suiza, trabajó en Hatch Ingeniería y en IM2 de Codelco, en proyectos de Codelco y Rio Tinto.Felipe es parte del Dpto. de Ingeniería de Minas de la Universidad de Chile como profesor adjunto. Actualmente está trabajando en su doctorado en el Laboratorio de Mecánica de Rocas de EPFL. Sus temas de interés están relacionados con mecánica de rocas, minería , túneles e ingeniería geologica.',
        'NAME_EX_FINANCES2': 'Álvaro Ayala',
        'BIO_EX_FINANCES2' : 'Álvaro es ingeniero civil y magíster en Recursos Hídricos y Medio Ambiente de la Universidad de Chile. En esta universidad, trabajó como ingeniero e investigador en distintos proyectos relacionados con hidrología de montaña, cambio climático y manejo de recursos hídricos. Actualmente es becario de Becas Chile y candidato a doctor en el grupo de Hidrología y Manejo de Recursos Hídricos de la ETH-Zurich. En este grupo continúa investigando procesos hidrológicos en regiones de montaña, con especial atención en los Andes.Álvaro vive desde 2012 en Zurich y participa en una constante colaboración científica entre investigadores en glaciología e hidrología de Suiza y Chile.',
        'TITLE_BUZON': 'Buzon Academico y Universitario',
        'DESC_SUMMARY_BUZON': 'El «Buzón Universitario» de PL fue creado hace 7 años con los directivos de entre 2008 y 2014: Julie Bauer (Suiza, UNI GE), José Parra ...',
        'TITLE_PAPAYAPODS': 'papayapods te ayuda a encontrar un departamento',
        'DESC_SUMMARY_PAPAYAPODS': 'Todos hemos tenido que mudarnos en más de una ocasión, lo cual puede ser una experiencia estresante, sobro todo en Suiza donde la demanda de ...',
        'TITLE_TRUMP': 'Our Director Dr. Rodrigo Polanco gives his vision on the recent election of Donald Trump in the United States',
        'DESC_SUMMARY_TRUMP': 'What does a Trump presidency mean for the developing world? After an 18-month campaign characterised by inward-looking nationalism and often racist vitriol, the idea that ...',
        'TITLE_ENCUENTRO_2016': 'Encuentro Ginebra 2016',
        'DESC_SUMMARY_ENCUENTRO_2016': 'El pasado 7 de mayo, en la Universidad de Ginebra, la Asociación de investigadores chilenos en Suiza (ICES) realizó su Encuentro 2016...',
        'TITLE_REGISTRO_CHILENOS': 'Segundo registro de chilenos que viven en el extranjero',
        'DESC_SUMMARY_REGISTRO_CHILENOS': 'El Instituto Nacional de Estadísticas junto al Ministerio de Relaciones Exteriores actualmente están llevando a cabo el “Segundo Registro de Chilenos en el Exterior...',
        'TITLE_AVISO_ENCUENTRO_2016': 'Save the date! ICES second meeting will take place in Geneva next 7th of May',
        'DESC_SUMMARY_AVISO_ENCUENTRO': 'This year the event will take place on Saturday May 7, 2016 from 10:00 to 19:30 at the University of Geneva. The meeting will be held under ...',
        'TITLE_CHILE_GLOBAL': 'Presentando a ICES en Encuentros ChileGlobal 2015',
        'DESC_CHILE_GLOBAL': 'El evento titulado: “Developing sustainable futures”, fue llevado a cabo, bajo la temática general del desarrollo de un futuro sustentable para Chile, como también para ...',
        'TITLE_CONSTRUYENDO_PUENTES': 'Primer Encuentro ICES: “Construyendo Puentes”',
        'DESC_CONSTRUYENDO_PUENTES': 'Todo un éxito resultó el primer evento de la asociación de Investigadores Chilenos en Suiza (ICES), para abordar el rol de la investigación científica y ...',
        'TITLE_ENCUENTRO_GLOBAL_2015': 'Encuentros ChileGlobal 2015',
        'DESC_ENCUENTRO_GLOBAL': 'Gran noticia desde Encuentros ChileGlobal 2015 Las Conferencias Encuentros son reuniones de ciencia y emprendimiento que congregan a investigadores y líderes de opinión, chilenos y extranjeros, ...',
        'TITLE_CREACION_ICES': 'Se crea oficialmente la Asociación de Investigadores Chilenos en Suiza – ICES',
        'DESC_CREACION_ICES' :'En Lausanne Cantón de Vaud, con no más de 2ºC de temperatura, se llevó a cabo la ceremonia simbólica de la Asamblea Constitutiva  de ICES ...',
        'TITLE_ETH_APOYO': 'ETH Global apoyará a ICES en nuestras primeras actividades',
        'DESC_ETH_APOYO': 'ETH Global – “La oficina internacional de ETH Zurich” – es la oficina responsable de implementar estrategias de desarrollo y colaboración global para ETH Zurich. ...',
        'TITLE_ICES_EMBAJADOR': 'Reunión de ICES con el embajador de Chile en Suiza',
        'DESC_ICES_EMBAJADOR': 'A partir de la amable invitación hecha por el embajador de Chile en Suiza, el Sr. José Luis Balmaceda y gracias a la coordinación por ...',
        'TITLE_BERNA_2014': 'En Berna se realiza la primera reunión de la asociación',
        'DESC_BERNA_2014': 'Coincidiendo con el espíritu pratiótico de la temporada, el 18 de septiembre de 2014 se reunió parte de quienes conformarían la directiva de la asociación ...',
        'CONTINUE': 'Continuar',
        'TITLE_ENCUENTRO_2017': 'Encuentro 2017 ICES en Berna',
        'DESC_ENCUENTRO_2017':'El evento se llevará a cabo el Sábado 20 de Mayo del 2017 de 09:00 a 17:00 horas en el Casino Kursaal Bern, Kornhausstrasse 3, 3000 Bern...'

    });

    $translateProvider.determinePreferredLanguage();
    $translateProvider.fallbackLanguage('en');
});