'use strict';

angular.module('ices').config(function($translateProvider) {
    $translateProvider.translations('en', {
        'TITLE': 'Hello',
        'FOO': 'This is a paragraph',
        'MENU_HOME': 'HOME',
        'MENU_ABOUT': 'ABOUT US',
        'MENU_MOTIVATION': 'Motivation',
        'MENU_GOAL': 'Objectives',
        'MENU_ORG': 'Structure',
        'MENU_DIRECTIVE': 'Directive',
        'MENU_EXDIRECTIVE':'Ex Directive',
        'MENU_STUDY': 'STUDY IN SWITZERLAND',
        'MENU_ICES': 'ICES COMMUNITY',
        'MENU_REQUIRIMENTS': 'Requirements',
        'MENU_BENEFITS': 'Benefits of being member',
        'MENU_MEMBERSHIP':'Annual membership',
        'MENU_SIGN_IN': 'Sign in form',
        'MENU_EVENT': 'EVENTS',
        'MENU_NEWS': 'NEWS',
        'MENU_PHOTO': 'PHOTOS',
        'MENU_CONTACT': 'CONTACT',
        'FOOTER_CONTACT_US': 'Contact us',
        'FOOTER_PARTNER':'Collaborators / Partners',
        'TITLE_ABOUT': 'About us?',
        'TITLE_MOTIVATION': 'What Motivates ICES?',
        'TITLE_GOAL': 'Objectives',
        'TITLE_PPAL_GOAL': 'These are our main objectives',
        'TITLE_ORG': 'Structure',
        'TITLE_OUR_ORG': 'Our structure',
        'TITLE_DIRECTIVE':'Directive',
        'TITLE_EX_DIRECTIVE': 'Ex Directive',
        'CAROUSEL_TEXT': 'ICES is constituted by researchers, students and professionals who work in Switzerland',
        'CAROUSEL_TEXT2': 'ICES is interested in the Chilean-Swiss collaborative research',
        'ABOUT_US': 'ICES (stands for the Spanish version of Chilean Researchers in Switzerland) is a non-profit association formed by a group of researchers, academics, students and professionals who develop their respective activities in Switzerland, interested in the collaboration between Chile and Switzerland in every field of knowledge and research.',
        'MOTIVATION': 'ICES seeks to contribute to the academic and professional collaboration between Chile and Switzerland. Based on our academic and professional experiences in Switzerland, we believe that there are many opportunities for scientific and professional collaboration between institutions of these two countries. We think that the academic, professional and even personal life of the Chilean researchers in Switzerland can profit from the advices and past experiences of people who are already working in this country. Our main motivation is to create the opportunities for Chilean researchers in Switzerland to contact each other, interchange experiences and explore new academic challenges together with Chilean and Swiss organizations. Also, we want to be an information platform in order to facilitate the exchange of Chilean students in Switzerland.',
        'GOAL': 'The objectives of our association can be divided in three main levels, going from the short-term in the first level to the long-term in the third:',
        'GOAL_LEVEL1': 'Level 1: Support Chilean researchers through their entire stay in Switzerland',
        'GOAL_LIST1_LEVEL1': 'Create an information platform for researchers and students in Chile interested in Switzerland for their academic and professional career opportunities.',
        'GOAL_LIST2_LEVEL1': 'Facilitate the integration of new Chilean researchers and students in Switzerland.',
        'GOAL_LIST3_LEVEL1': 'Strengthen the academic and scientific links between Chilean researchers, academics, students and professionals living in Switzerland.',
        'GOAL_LEVEL2': 'Level 2: Promotion of scientific and professional collaboration between Chilean and Swiss institutions and individuals',
        'GOAL_LIST1_LEVEL2': 'Create a platform where Chilean and Swiss researchers and students can share information, solve questions and find project partners or career opportunities in both countries.',
        'GOAL_LIST2_LEVEL2': 'Foster the development of new scientific and academic projects and initiatives involving both countries.',
        'GOAL_LIST3_LEVEL2':'Show Chile in Switzerland as a valuable opportunity for research and collaboration.',
        'GOAL_LEVEL3': 'Level 3: Participate in the discussion for the scientific and academic development of Chile',
        'GOAL_LIST1_LEVEL3': 'Participate and collaborate with different associations and networks of Chilean researchers in Chile and abroad.',
        'GOAL_LIST2_LEVEL3': 'Contribute from our experience to the development of policies for the reintegration of researchers and students returning to Chile. In particular, we would like to help students that are part of the Becas Chile program for post-graduate studies.'
    });

    $translateProvider.translations('es', {
        'TITLE': 'Hola',
        'FOO': 'Este es un párrafo',
        'MENU_HOME': 'HOME',
        'MENU_ABOUT': 'QUIENES SOMOS',
        'MENU_MOTIVATION': 'Motivacion',
        'MENU_GOAL': 'Objetivos de la asociacion',
        'MENU_ORG': 'Organizacion',
        'MENU_DIRECTIVE': 'Directiva',
        'MENU_EXDIRECTIVE':'Directiva 2015-2016',
        'MENU_STUDY': 'ESTUDIA EN SUIZA',
        'MENU_ICES': 'COMUNIDAD ICES',
        'MENU_REQUIRIMENTS': 'Requisitos',
        'MENU_BENEFITS': 'Beneficios de ser miembro',
        'MENU_MEMBERSHIP':'Membresia anual',
        'MENU_SIGN_IN': 'Formulario de registro',
        'MENU_EVENT': 'EVENTOS',
        'MENU_NEWS': 'NOTICIAS',
        'MENU_PHOTO': 'FOTOS',
        'MENU_CONTACT': 'CONTACTO',
        'FOOTER_CONTACT_US': 'Contactanos',
        'FOOTER_PARTNER':'Colaboradores / Socios',
        'TITLE_ABOUT': 'Quienes Somos?',
        'TITLE_MOTIVATION': 'Que motiva a ICES',
        'TITLE_GOAL': 'Objetivos de la asociacion',
        'TITLE_PPAL_GOAL': 'Estos son nuestros principales objetivos',
        'TITLE_ORG': 'Organizacion',
        'TITLE_OUR_ORG': 'Nuestra organizacion',
        'TITLE_DIRECTIVE':'Directiva',
        'TITLE_EX_DIRECTIVE': 'Ex Directiva',
        'CAROUSEL_TEXT': 'ICES esta conformada por investigadores, academicos, estudiantes y profesionales que trabajan en Suiza',
        'CAROUSEL_TEXT2': 'ICES se interesa en la colaboracion Chileno-Suiza en investigacion',
        'ABOUT_US': 'ICES (Investigadores Chilenos en Suiza) es una asociación sin fines de lucro conformada por un grupo de investigadores, académicos, estudiantes y profesionales que desarrollan sus respectivas actividades en Suiza, interesados en aportar a la colaboración chileno-suiza en todas las áreas de la investigación y el conocimiento.',
        'MOTIVATION': 'ICES busca ser un aporte a la colaboración académica y profesional entre Chile y Suiza. Basados en nuestras experiencias académicas y profesionales en Suiza, creemos que existe un amplio espacio para la colaboración científica y profesional entre personas e instituciones suizas y chilenas. Creemos que la vida académica, profesional e incluso personal de los investigadores chilenos en Suiza se puede beneficiar de los consejos y experiencias pasadas de chilenos que ya se encuentran trabajando en Suiza. Nuestra motivación principal es crear un espacio donde los investigadores chilenos desempeñándose en Suiza puedan contactarse, intercambiar experiencias y explorar nuevos desafíos académicos junto a organizaciones chilenas y suizas, así como también ser una plataforma de información para facilitar el intercambio de estudiantes chilenos en Suiza.',
        'GOAL': 'Los objetivos de la asociación se dividen en tres niveles, los que van desde objetivos de corto plazo en el primer nivel hasta objetivos de largo plazo en el tercero:',
        'GOAL_LEVEL1': 'Nivel 1: Apoyar a investigadores chilenos durante toda su estadía en Suiza.',
        'GOAL_LIST1_LEVEL1': 'Crear una plataforma de información para investigadores y estudiantes en Chile interesados en Suiza en busca de oportunidades académicas y profesionales.',
        'GOAL_LIST2_LEVEL1': 'Facilitar la integración de nuevos investigadores y estudiantes chilenos en Suiza.',
        'GOAL_LIST3_LEVEL1': 'Fortalecer los lazos académicos y científicos entre investigadores, académicos, estudiantes y profesionales chilenos viviendo en Suiza.',
        'GOAL_LEVEL2': 'Nivel 2: Promover la colaboración científica y profesional entre personas e instituciones chilenas y suizas.',
        'GOAL_LIST1_LEVEL2': 'Crear una plataforma donde investigadores y estudiantes chilenos y suizos compartan información, resuelvan dudas y encuentren socios de colaboración u oportunidades laborales en ambos países.',
        'GOAL_LIST2_LEVEL2': 'Incentivar el desarrollo de proyectos e iniciativas científicas y académicas en ambos países.Mostrar Chile en Suiza como una valiosa oportunidad para la cooperación científica.',
        'GOAL_LIST3_LEVEL2':' Mostrar Chile en Suiza como una valiosa oportunidad para la cooperación científica.',
        'GOAL_LEVEL3': 'Nivel 3: Participar en la discusión sobre el desarrollo científico y académico en Chile.',
        'GOAL_LIST1_LEVEL3': 'Participar y colaborar con distintas asociaciones y redes de investigadores chilenos en el extranjero.',
        'GOAL_LIST2_LEVEL3': 'Contribuir desde nuestra experiencia al desarrollo de políticas para la reintegración de investigadores y estudiantes que vuelven a Chile. En particular, buscamos ayudar a los estudiantes que participan del programa Becas Chile.'
    });

    $translateProvider.determinePreferredLanguage();
    $translateProvider.fallbackLanguage('en');
});